site_name: LeCloudFacile K8S Training
site_url: https://lecloudfacile.com/
nav:
  - Présentation Générale:
    - 'Home': index.md
    - 'Syllabus': 00-presentation/syllabus.md
    - 'Team': 00-presentation/team.md
  - 'Prerequis':
    - '01 - cours': 01-prerequis/cours.md
    - '01 - Lab': 01-prerequis/lab.md

theme: readthedocs
extra_css: [style.css]
markdown_extensions:
  - toc:
      permalink: "#"
      separator: "_"
